version: "3.5"
services:
  drdwns:
    image: garretsidzaka/docker-remote-desktop-wine-nosound:latest
    hostname: docker-desktop
    restart: unless-stopped
    environment:
        - TZ=UTC
        - WINEARCH=win64
        - WINEPREFIX=/root/.wine
    ports:
        - "3389:3389/tcp"
    volumes:
        - drdwine:/root/.wine
volumes:
  drdwine:

